version: "3.9"

services:
  headless-proxy:
    image: zytedata/zyte-smartproxy-headless-proxy:latest
    container_name: zyte-smartproxy-headless-proxy
    ports:
      - "${SPM_LOCAL_PORT:-3128}:3128"
    environment:
      CRAWLERA_HEADLESS_BINDIP: "0.0.0.0"
      CRAWLERA_HEADLESS_BINDPORT: "3128"
      CRAWLERA_HEADLESS_APIKEY: "${CRAWLERA_API_KEY}"
      CRAWLERA_HEADLESS_CHOST: "${CRAWLERA_HOST:-proxy.crawlera.com}"
      CRAWLERA_HEADLESS_CPORT: "${CRAWLERA_PORT:-8010}"
      CRAWLERA_HEADLESS_NOAUTOSESSIONS: "${CRAWLERA_NO_AUTO_SESSIONS:-false}"
      CRAWLERA_HEADLESS_CONCURRENCY: "${CRAWLERA_CONCURRENT_CONNECTIONS:-0}"
      CRAWLERA_HEADLESS_DONTVERIFY: "${CRAWLERA_DONT_VERIFY:-false}"
      CRAWLERA_HEADLESS_XHEADERS: "${CRAWLERA_XHEADERS:-}"
    restart: unless-stopped
